### PR TITLE
Enable Windows build

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ryanvolz** [comment]
So the many
```
error C3615: constexpr function 'mobilinkd::convolve_bit' cannot result in a constant expression
```
or similar errors are happening because the MSVC `__popcnt` function is not a fully suitable substitute for `__builtin_popcount`. The former always inserts the processor's `popcnt` instruction, while the latter also allows a fallback that can be evaluated at compile-time in a `constexpr` function. So I think the solution will be to drop the `constexpr` (probably undesirable from a performance standpoint and from needing a bunch of intrusive ifdefs) or come up with an alternative implementation that allows `constexpr`. Volk has a generic one [here](https://github.com/gnuradio/volk/blob/main/kernels/volk/volk_32u_popcnt.h) that might be usable. I'm doing some reading to see if there are other options.

**Comment by ryanvolz** [comment]
Looks like `std::popcount` should work and it's available from VS 2019 16.5 with C++20 support enabled. I'm giving that a try.

**Comment by ryanvolz** [comment]
Getting very close! I'm going to take a quick break and hope to get back to this in a couple hours and finish it off.

**Review by n1ai — APPROVED** [review]
I approve.
Dave, N1Ai

**Pull request merged**
